// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isevdfbjmaknnrvznnax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZXZkZmJqbWFrbm5ydnpubmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzcxNjQsImV4cCI6MjA3MDMxMzE2NH0.s2_5K95UrqLt13No7NT_g4yw1EayEIJ31DeiV7oHpcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});